"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *
from serpapi.constant import *

class AppleAppStoreSearch(SerpApiClient):
    """AppleAppStoreSearch enables to search google scholar and parse the result.
    ```python
    from serpapi import AppleAppStoreSearch
    search = AppleAppStoreSearch({"term": "ipad"})
    data = search.get_dct()
    ```
    
    doc: https://serpapi.com/apple-app-store
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


