"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *

class BaiduSearch(SerpApiClient):
    """BaiduSearch enables to search baidu and parse the result.
    ```python
    from serpapi import BaiduSearch
    query = BaiduSearch({"q": "coffee"})
    data = query.get_json()
    ```

    doc: https://serpapi.com/baidu-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


