"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *
from serpapi.constant import *

class DuckDuckGoSearch(SerpApiClient):
    """DuckDuckGoSearch enables to search google scholar and parse the result.
    ```python
    from serpapi import DuckDuckGoSearch
    search = DuckDuckGoSearch({"query": "chair"})
    data = search.get_json()
    ```

    doc: https://serpapi.com/duckduckgo-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


