"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *

class HomeDepotSearch(SerpApiClient):
    """HomeDepotSearch enables to search home depot and parse the result.
    ```python
    from serpapi import HomeDepotSearch
    query = HomeDepotSearch({"q": "chair"})
    data = query.get_json()
    ```

    doc: https://serpapi.com/home-depot-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


