"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *
from serpapi.constant import *

class NaverSearch(SerpApiClient):
    """NaverSearch enables to search google scholar and parse the result.
    ```python
    from serpapi import NaverSearch
    search = NaverSearch({"query": "chair"})
    data = search.get_dict()
    ```

    doc: https://serpapi.com/naver-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


