"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *
from serpapi.constant import *

class WalmartSearch(SerpApiClient):
    """WalmartSearch enables to search google scholar and parse the result.
    ```python
    from serpapi import WalmartSearch
    search = WalmartSearch({"query": "chair"})
    data = search.get_dict()
    ```

    doc: https://serpapi.com/walmart-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


