"""
This type stub file was generated by pyright.
"""

from serpapi.serp_api_client import *

class YoutubeSearch(SerpApiClient):
    """YoutubeSearch enables to search google scholar and parse the result.
    ```python
    from serpapi import YoutubeSearch
    query = YoutubeSearch({"search_query": "chair"})
    data = query.get_dict()
    ```

    doc: https://serpapi.com/youtube-search-api
    """
    def __init__(self, params_dict) -> None:
        ...
    
    def get_location(self, q, limit=...):
        ...
    


